version: '2'
x-redash-service: &redash-service
  image: redash/redash:7.0.0.b18042
  links:
    - postgres
    - redis
  env_file: .env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.5-alpine
    env_file: .env
    restart: always
  nginx:
    build: ./build/nginx
    ports:
      - "8080:80"
    links:
      - server:redash
    restart: always
    environment:
      REDASH_HOST: "redash"
    command: /bin/bash -c "envsubst '$$REDASH_HOST' < /etc/nginx/conf.d/redash.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
